### ISSUE TITLE
无法找到hook点

### ISSUE THREAD

**Issue by MomentDerek** [XhyEax/SoftApHelper#8]
多谢大大写的模块，但是不知道为什么失效了

![Screenshot_2022-11-15-23-32-45-308_com.android.shell.jpg](https://user-images.githubusercontent.com/40252940/201960100-862f1e4b-8543-497c-a802-e8dae70e5a1f.jpg)

```
[ 2022-11-15T23:24:15.739     1000:  1660:  1660 E/LSPosed-Bridge  ] de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: android.net.ip.IpServer
	at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:12)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(Unknown Source:0)
	at com.xhy.xp.softaphelper.MainHook.handleLoadPackage(MainHook.java:81)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at q.beforeHookedMethod(Unknown Source:167)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.startBootstrapServices(Unknown Source:11)
	at com.android.server.SystemServer.run(SystemServer.java:901)
	at com.android.server.SystemServer.main(SystemServer.java:623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1051)
Caused by: java.lang.ClassNotFoundException: android.net.ip.IpServer
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at o.a(Unknown Source:20)
	at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:4)
	... 13 more
Caused by: java.lang.ClassNotFoundException: android.net.ip.IpServer
	... 17 more
```

**Comment by XhyEax** [comment]
你先试试修改成功没有。报错是因为其他系统服务也会走到这来，不影响正常使用。

连接测试：
手机端使用`ifconfig`命令查看ip，或者使用其他机器连接热点后，`ping 192.168.43.1`。

**Comment by XhyEax** [comment]
可以打开`/apex/com.android.tethering/priv-app/InProcessTethering/InProcessTethering.apk`，反编译看看。
查看`android.net.ip.IpServer`类和`requestIpv4Address`函数是否存在。

**Comment by MomentDerek** [comment]
是修改成功的，我读到其他的ip去了，指定网卡后搞定，多谢解答
